version: '3.7'
services:
  db:
    image: postgres:12-alpine
    env_file: .env
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  culturameta:
    build: ./culturameta
    command: [ "./wait-for-it.sh", "db:5432", "--",
               "python", "manage.py", "runserver",  "0.0.0.0:8000" ]
    env_file: .env
    volumes:
      - ./culturameta:/src
    depends_on:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=culturameta.settings.local
    ports:
      - '8000:8000'
