# Generated by Django 3.2 on 2021-04-29 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Nombre ', max_length=50, null=True, verbose_name='Nombre ')),
                ('description', models.TextField(blank=True, help_text='Descripcion', null=True, verbose_name='Descripcion')),
                ('icono', models.ImageField(blank=True, help_text='Icono', max_length=50, null=True, upload_to='', verbose_name='Icono ')),
            ],
            options={
                'verbose_name': ('Area',),
                'verbose_name_plural': 'Areas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Nombre del Artista', max_length=20, null=True, verbose_name='Nombre')),
                ('last_name', models.CharField(blank=True, help_text='Apellidos del Artista', max_length=20, null=True, verbose_name='Apellidos')),
                ('age', models.PositiveBigIntegerField(blank=True, help_text='Edad', null=True, verbose_name='Edad')),
                ('cedula', models.PositiveBigIntegerField(blank=True, help_text='Cedula', null=True, verbose_name='Cedula')),
                ('lugar_nacimiento', models.CharField(blank=True, help_text='Lugar de nacimiento', max_length=20, null=True, verbose_name='Lugar de nacimiento')),
            ],
            options={
                'verbose_name': ('Artista',),
                'verbose_name_plural': 'Artista',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Biblioteca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Nombre ', max_length=50, null=True, verbose_name='Nombre ')),
                ('libro', models.CharField(blank=True, help_text='Libro', max_length=50, null=True, verbose_name='Libro')),
                ('description', models.TextField(blank=True, help_text='Descripcion', null=True, verbose_name='Descripcion')),
                ('orden', models.PositiveBigIntegerField(blank=True, help_text='Orden', null=True, verbose_name='Orden')),
            ],
            options={
                'verbose_name': ('Biblioteca',),
                'verbose_name_plural': 'Biblioteca',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Festival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Nombre ', max_length=50, null=True, verbose_name='Nombre ')),
                ('descripcion', models.CharField(blank=True, help_text='Descripción', max_length=50, null=True, verbose_name='Descripción')),
                ('orden', models.PositiveBigIntegerField(blank=True, help_text='Orden', null=True, verbose_name='Orden')),
                ('fecha', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': ('Festival',),
                'verbose_name_plural': 'Festival',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Nombre ', max_length=50, null=True, verbose_name='Nombre ')),
                ('descripcion', models.CharField(blank=True, help_text='Descripción', max_length=50, null=True, verbose_name='Descripción')),
                ('orden', models.PositiveBigIntegerField(blank=True, help_text='Orden', null=True, verbose_name='Orden')),
            ],
            options={
                'verbose_name': ('Noticia',),
                'verbose_name_plural': 'Noticia',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Nombre ', max_length=50, null=True, verbose_name='Nombre ')),
                ('name_obra', models.CharField(blank=True, help_text='Nombre de la obra', max_length=50, null=True, verbose_name='Nombre de la obra')),
                ('artista', models.CharField(blank=True, help_text='Nombre del artista', max_length=50, null=True, verbose_name='Nombre del artista')),
                ('ubicacion', models.CharField(blank=True, help_text='Nombre de archivo', max_length=50, null=True, verbose_name='Nombre de archivo')),
                ('description', models.TextField(blank=True, help_text='Descripcion', null=True, verbose_name='Descripcion')),
                ('image', models.ImageField(blank=True, help_text='Imagen ', max_length=50, null=True, upload_to='', verbose_name='Imagen ')),
            ],
            options={
                'verbose_name': ('Obra',),
                'verbose_name_plural': 'Obras',
                'ordering': ['id'],
            },
        ),
    ]
