# Generated by Django 3.2 on 2021-08-15 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arteycultura', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='area',
            old_name='description',
            new_name='description1',
        ),
        migrations.RemoveField(
            model_name='festival',
            name='fecha',
        ),
        migrations.AddField(
            model_name='area',
            name='description2',
            field=models.TextField(blank=True, help_text='Descripcion', null=True, verbose_name='Descripcion'),
        ),
        migrations.AddField(
            model_name='area',
            name='history',
            field=models.TextField(blank=True, help_text='Historia', null=True, verbose_name='Historia'),
        ),
        migrations.AddField(
            model_name='area',
            name='information',
            field=models.TextField(blank=True, help_text='Informacion', null=True, verbose_name='Informacion'),
        ),
        migrations.AddField(
            model_name='area',
            name='tittle1',
            field=models.CharField(blank=True, help_text='Titulo ', max_length=200, null=True, verbose_name='Titulo  '),
        ),
        migrations.AddField(
            model_name='area',
            name='tittle2',
            field=models.CharField(blank=True, help_text='Titulo ', max_length=200, null=True, verbose_name='Titulo  '),
        ),
        migrations.AddField(
            model_name='biblioteca',
            name='adress',
            field=models.CharField(blank=True, help_text='Dirección', max_length=200, null=True, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='biblioteca',
            name='history',
            field=models.TextField(blank=True, help_text='Historia', null=True, verbose_name='Historia'),
        ),
        migrations.AddField(
            model_name='biblioteca',
            name='librarian',
            field=models.CharField(blank=True, help_text='Bibliotecario', max_length=200, null=True, verbose_name='Bibliotecario'),
        ),
        migrations.AddField(
            model_name='biblioteca',
            name='resolution',
            field=models.CharField(blank=True, help_text='Resolucion', max_length=200, null=True, verbose_name='Resolucion'),
        ),
        migrations.AddField(
            model_name='biblioteca',
            name='zone',
            field=models.CharField(blank=True, help_text='ZOna', max_length=200, null=True, verbose_name='ZOna'),
        ),
        migrations.AddField(
            model_name='noticia',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=' noticia/imagen', verbose_name='URL Document'),
        ),
        migrations.AlterField(
            model_name='area',
            name='icono',
            field=models.ImageField(blank=True, help_text='Icono', max_length=200, null=True, upload_to='', verbose_name='Icono '),
        ),
        migrations.AlterField(
            model_name='area',
            name='name',
            field=models.CharField(blank=True, help_text='Nombre ', max_length=200, null=True, verbose_name='Nombre '),
        ),
        migrations.AlterField(
            model_name='artista',
            name='last_name',
            field=models.CharField(blank=True, help_text='Apellidos del Artista', max_length=200, null=True, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='artista',
            name='lugar_nacimiento',
            field=models.CharField(blank=True, help_text='Lugar de nacimiento', max_length=200, null=True, verbose_name='Lugar de nacimiento'),
        ),
        migrations.AlterField(
            model_name='artista',
            name='name',
            field=models.CharField(blank=True, help_text='Nombre del Artista', max_length=200, null=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='biblioteca',
            name='libro',
            field=models.CharField(blank=True, help_text='Libro', max_length=200, null=True, verbose_name='Libro'),
        ),
        migrations.AlterField(
            model_name='biblioteca',
            name='name',
            field=models.CharField(blank=True, help_text='Nombre ', max_length=200, null=True, verbose_name='Nombre '),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripción', max_length=50, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='name',
            field=models.CharField(blank=True, help_text='Nombre ', max_length=300, null=True, verbose_name='Nombre '),
        ),
        migrations.AlterField(
            model_name='obra',
            name='image',
            field=models.ImageField(blank=True, help_text='Imagen ', max_length=200, null=True, upload_to='', verbose_name='Imagen '),
        ),
        migrations.AlterField(
            model_name='obra',
            name='name',
            field=models.CharField(blank=True, help_text='Nombre ', max_length=200, null=True, verbose_name='Nombre '),
        ),
        migrations.AlterField(
            model_name='obra',
            name='ubicacion',
            field=models.CharField(blank=True, help_text='Nombre de archivo', max_length=200, null=True, verbose_name='Nombre de archivo'),
        ),
    ]
