# Generated by Django 3.2 on 2021-04-29 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre ', max_length=50, verbose_name='Nombre ')),
                ('contact', models.CharField(help_text='Contacto', max_length=50, verbose_name='Contacto')),
                ('carge', models.CharField(help_text='Cargo', max_length=50, verbose_name='Cargo')),
                ('extension', models.TextField(help_text='Extension telefono', verbose_name='Extension telefono')),
                ('phone', models.TextField(help_text='Telefono', verbose_name='Telefono')),
                ('fax', models.TextField(help_text='Fax', verbose_name='Fax')),
                ('email', models.TextField(help_text='Correo electronico', verbose_name='Correo electronico')),
            ],
            options={
                'verbose_name': ('Empleado',),
                'verbose_name_plural': 'Empleados',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre ', max_length=50, verbose_name='Nombre ')),
                ('type', models.CharField(help_text='Tipo de sede', max_length=50, verbose_name='Tipo de sede')),
                ('adress', models.CharField(help_text='Direccion', max_length=50, verbose_name='Direccion')),
                ('city', models.TextField(help_text='Municipio', verbose_name='Municipio')),
                ('phone', models.TextField(help_text='Telefono', verbose_name='Telefono')),
                ('fax', models.TextField(help_text='Fax', verbose_name='Fax')),
                ('email', models.TextField(help_text='Correo electronico', verbose_name='Correo electronico')),
            ],
            options={
                'verbose_name': ('Sede',),
                'verbose_name_plural': 'Sede',
                'ordering': ['id'],
            },
        ),
    ]
