# Generated by Django 3.2 on 2021-08-04 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employed',
            name='email',
            field=models.EmailField(help_text='Correo electronico', max_length=254, verbose_name='Correo electronico'),
        ),
        migrations.AlterField(
            model_name='employed',
            name='fax',
            field=models.CharField(help_text='Fax', max_length=20, verbose_name='Fax'),
        ),
        migrations.AlterField(
            model_name='employed',
            name='phone',
            field=models.IntegerField(help_text='Telefono', verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='sede',
            name='email',
            field=models.EmailField(help_text='Correo electronico', max_length=254, verbose_name='Correo electronico'),
        ),
        migrations.AlterField(
            model_name='sede',
            name='fax',
            field=models.CharField(help_text='Fax', max_length=20, verbose_name='Fax'),
        ),
        migrations.AlterField(
            model_name='sede',
            name='phone',
            field=models.IntegerField(help_text='Telefono', verbose_name='Telefono'),
        ),
    ]
