# Generated by Django 3.2 on 2021-08-15 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0002_auto_20210804_1343'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coro', models.TextField(blank=True, help_text='Coro', null=True, verbose_name='Coro')),
            ],
        ),
        migrations.CreateModel(
            name='Functions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function', models.TextField(blank=True, help_text='Función', null=True, verbose_name='Función')),
            ],
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta', models.TextField(blank=True, help_text='Meta', null=True, verbose_name='Meta')),
                ('loft', models.TextField(blank=True, help_text='Altillanura', null=True, verbose_name='Altillanura')),
                ('generalities', models.TextField(blank=True, help_text='Generalidades', null=True, verbose_name='Generalidades')),
                ('location', models.TextField(blank=True, help_text='Localizacion', null=True, verbose_name='Localizacion')),
                ('limits', models.TextField(blank=True, help_text='limites', null=True, verbose_name='limites')),
                ('aspects', models.TextField(blank=True, help_text='Aspectos', null=True, verbose_name='Aspectos')),
                ('economy', models.TextField(blank=True, help_text='Economia', null=True, verbose_name='Economia')),
                ('territory', models.TextField(blank=True, help_text='Territorio', null=True, verbose_name='Territorio')),
                ('height', models.TextField(blank=True, help_text='Altura', null=True, verbose_name='Altura')),
                ('temperature', models.TextField(blank=True, help_text='Temperatura', null=True, verbose_name='Temperatura')),
                ('regions', models.TextField(blank=True, help_text='Regiones', null=True, verbose_name='Regiones')),
                ('hydrography', models.TextField(blank=True, help_text='Información', null=True, verbose_name='Información')),
            ],
        ),
        migrations.CreateModel(
            name='MiVi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mision', models.CharField(blank=True, help_text='Mision', max_length=20, null=True, verbose_name='Mision')),
                ('descriptionmision', models.TextField(blank=True, help_text='Descripción mision', null=True, verbose_name='Descripción mision')),
                ('vision', models.CharField(blank=True, help_text='Vision', max_length=20, null=True, verbose_name='Vision')),
                ('descriptionvision', models.TextField(blank=True, help_text='Descripción Vision', null=True, verbose_name='Descripción Vision')),
            ],
        ),
        migrations.CreateModel(
            name='Objectives',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objetive', models.TextField(blank=True, help_text='Objetivo', null=True, verbose_name='Objetivo')),
            ],
        ),
    ]
