# Generated by Django 3.2 on 2021-08-30 10:47

from django.db import migrations, models
import information.models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0004_auto_20210830_0140'),
    ]

    operations = [
        migrations.AddField(
            model_name='pqrsd',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='6.Municipio'),
        ),
        migrations.AlterField(
            model_name='pqrsd',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='pqrsd/file', validators=[information.models.file_size], verbose_name='11.Archivo adjunto'),
        ),
        migrations.AlterField(
            model_name='pqrsd',
            name='asunto',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='9.Asunto '),
        ),
        migrations.AlterField(
            model_name='pqrsd',
            name='email',
            field=models.EmailField(blank=True, max_length=30, null=True, verbose_name='7.Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='pqrsd',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='8.Celular'),
        ),
        migrations.AlterField(
            model_name='pqrsd',
            name='solicitud',
            field=models.TextField(blank=True, null=True, verbose_name='10.Descripción Solicitud'),
        ),
    ]
