# Generated by Django 3.2 on 2021-08-30 10:59

from django.db import migrations, models
import django.db.models.deletion
import document.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accountability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountability', models.CharField(blank=True, help_text='Rendición de cuentas ', max_length=100, null=True, verbose_name='Rendición de cuentas ')),
                ('url', models.CharField(blank=True, help_text='Url', max_length=50, null=True, verbose_name='Url')),
                ('file', models.FileField(blank=True, null=True, upload_to=' document/rendicion', verbose_name='URL Document')),
            ],
            options={
                'verbose_name': ('Rendicion de cuentas',),
                'verbose_name_plural': 'Rendicion de cuentas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre ', max_length=50, verbose_name='Nombre ')),
                ('imagen', models.ImageField(help_text='Imagen ', upload_to='', verbose_name='Imagen ')),
            ],
            options={
                'verbose_name': ('Imagen',),
                'verbose_name_plural': 'Imagen',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre ', max_length=50, verbose_name='Nombre ')),
            ],
            options={
                'verbose_name': ('Menu',),
                'verbose_name_plural': 'Menu',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre ', max_length=50, verbose_name='Nombre ')),
                ('menu', models.ForeignKey(help_text='Menu', on_delete=django.db.models.deletion.DO_NOTHING, to='document.menu', verbose_name='Menu')),
            ],
            options={
                'verbose_name': ('Modulo',),
                'verbose_name_plural': 'Modulo',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SubModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre ', max_length=50, verbose_name='Nombre ')),
                ('module', models.ForeignKey(help_text='Modulo', on_delete=django.db.models.deletion.DO_NOTHING, to='document.module', verbose_name='Modulo')),
            ],
            options={
                'verbose_name': ('Sub modulo',),
                'verbose_name_plural': 'Sub modulo',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Nombre ', max_length=100, null=True, verbose_name='Nombre ')),
                ('name_archive', models.CharField(blank=True, help_text='Nombre de archivo', max_length=100, null=True, verbose_name='Nombre de archivo')),
                ('age', models.CharField(blank=True, help_text='Año', max_length=100, null=True, verbose_name='Año')),
                ('month', models.CharField(blank=True, help_text='Mes', max_length=50, null=True, verbose_name='Mes')),
                ('description', models.TextField(blank=True, help_text='Descripcion', null=True, verbose_name='Descripcion')),
                ('orden', models.PositiveBigIntegerField(blank=True, help_text='Orden', null=True, verbose_name='Orden')),
                ('url', models.FileField(blank=True, null=True, upload_to='document/file', verbose_name='URL Document')),
                ('module', models.ForeignKey(blank=True, help_text='Modulo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='document.module', verbose_name='Modulo')),
                ('submodule', models.ForeignKey(blank=True, help_text='SubModulo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='document.submodule', verbose_name='Submodulo')),
            ],
            options={
                'verbose_name': ('Presupuesto',),
                'verbose_name_plural': 'Presupuesto',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Nombre ', max_length=200, null=True, verbose_name='Nombre ')),
                ('name_archive', models.CharField(blank=True, help_text='Nombre de archivo', max_length=200, null=True, verbose_name='Nombre de archivo')),
                ('age', models.CharField(blank=True, help_text='Año', max_length=100, null=True, verbose_name='Año')),
                ('month', models.CharField(blank=True, help_text='Mes', max_length=50, null=True, verbose_name='Mes')),
                ('description', models.TextField(blank=True, help_text='Descripcion', null=True, verbose_name='Descripcion')),
                ('orden', models.PositiveBigIntegerField(blank=True, help_text='Orden', null=True, verbose_name='Orden')),
                ('url', models.FileField(blank=True, null=True, upload_to=document.models.documents_path, validators=[document.models.file_size], verbose_name='URL Document')),
                ('module', models.ForeignKey(blank=True, help_text='Modulo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='document.module', verbose_name='Modulo')),
                ('submodule', models.ForeignKey(blank=True, help_text='SubModulo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='document.submodule', verbose_name='Submodulo')),
            ],
            options={
                'verbose_name': ('Document',),
                'verbose_name_plural': 'Document',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Controlinterno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Nombre ', max_length=100, null=True, verbose_name='Nombre ')),
                ('name_archive', models.CharField(blank=True, help_text='Nombre de archivo', max_length=100, null=True, verbose_name='Nombre de archivo')),
                ('age', models.CharField(blank=True, help_text='Año', max_length=100, null=True, verbose_name='Año')),
                ('month', models.CharField(blank=True, help_text='Mes', max_length=50, null=True, verbose_name='Mes')),
                ('description', models.TextField(blank=True, help_text='Descripcion', null=True, verbose_name='Descripcion')),
                ('orden', models.PositiveBigIntegerField(blank=True, help_text='Orden', null=True, verbose_name='Orden')),
                ('url', models.FileField(blank=True, null=True, upload_to=document.models.documents_path, verbose_name='URL Document')),
                ('module', models.ForeignKey(blank=True, help_text='Modulo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='document.module', verbose_name='Modulo')),
                ('submodule', models.ForeignKey(blank=True, help_text='SubModulo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='document.submodule', verbose_name='Submodulo')),
            ],
            options={
                'verbose_name': ('Control Interno',),
                'verbose_name_plural': 'Control Interno',
                'ordering': ['id'],
            },
        ),
    ]
