# Generated by Django 3.2 on 2021-04-29 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre ', max_length=50, verbose_name='Nombre ')),
                ('imagen', models.ImageField(help_text='Imagen ', upload_to='', verbose_name='Imagen ')),
            ],
            options={
                'verbose_name': ('Imagen',),
                'verbose_name_plural': 'Imagen',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre ', max_length=50, verbose_name='Nombre ')),
            ],
            options={
                'verbose_name': ('Menu',),
                'verbose_name_plural': 'Menu',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre ', max_length=50, verbose_name='Nombre ')),
                ('menu', models.ForeignKey(help_text='Menu', on_delete=django.db.models.deletion.DO_NOTHING, to='document.menu', verbose_name='Menu')),
            ],
            options={
                'verbose_name': ('Modulo',),
                'verbose_name_plural': 'Modulo',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SubModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre ', max_length=50, verbose_name='Nombre ')),
                ('module', models.ForeignKey(help_text='Modulo', on_delete=django.db.models.deletion.DO_NOTHING, to='document.module', verbose_name='Modulo')),
            ],
            options={
                'verbose_name': ('Sub modulo',),
                'verbose_name_plural': 'Sub modulo',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre ', max_length=50, verbose_name='Nombre ')),
                ('name_archive', models.CharField(help_text='Nombre de archivo', max_length=50, verbose_name='Nombre de archivo')),
                ('description', models.TextField(help_text='Descripcion', verbose_name='Descripcion')),
                ('orden', models.PositiveBigIntegerField(help_text='Orden', verbose_name='Orden')),
                ('module', models.ForeignKey(help_text='Modulo', on_delete=django.db.models.deletion.DO_NOTHING, to='document.module', verbose_name='Modulo')),
                ('submodule', models.ForeignKey(help_text='SubModulo', on_delete=django.db.models.deletion.DO_NOTHING, to='document.submodule', verbose_name='Submodulo')),
            ],
            options={
                'verbose_name': ('Document',),
                'verbose_name_plural': 'Document',
                'ordering': ['id'],
            },
        ),
    ]
