# Generated by Django 3.2 on 2021-08-04 18:43

from django.db import migrations, models
import django.db.models.deletion
import document.models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='age',
            field=models.CharField(blank=True, help_text='Año', max_length=100, null=True, verbose_name='Año'),
        ),
        migrations.AddField(
            model_name='document',
            name='month',
            field=models.CharField(blank=True, help_text='Mes', max_length=50, null=True, verbose_name='Mes'),
        ),
        migrations.AddField(
            model_name='document',
            name='url',
            field=models.FileField(blank=True, null=True, upload_to=document.models.documents_path, verbose_name='URL Document'),
        ),
        migrations.AlterField(
            model_name='document',
            name='description',
            field=models.TextField(blank=True, help_text='Descripcion', null=True, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='document',
            name='module',
            field=models.ForeignKey(blank=True, help_text='Modulo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='document.module', verbose_name='Modulo'),
        ),
        migrations.AlterField(
            model_name='document',
            name='name',
            field=models.CharField(blank=True, help_text='Nombre ', max_length=50, null=True, verbose_name='Nombre '),
        ),
        migrations.AlterField(
            model_name='document',
            name='name_archive',
            field=models.CharField(blank=True, help_text='Nombre de archivo', max_length=50, null=True, verbose_name='Nombre de archivo'),
        ),
        migrations.AlterField(
            model_name='document',
            name='orden',
            field=models.PositiveBigIntegerField(blank=True, help_text='Orden', null=True, verbose_name='Orden'),
        ),
        migrations.AlterField(
            model_name='document',
            name='submodule',
            field=models.ForeignKey(blank=True, help_text='SubModulo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='document.submodule', verbose_name='Submodulo'),
        ),
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Nombre ', max_length=100, null=True, verbose_name='Nombre ')),
                ('name_archive', models.CharField(blank=True, help_text='Nombre de archivo', max_length=100, null=True, verbose_name='Nombre de archivo')),
                ('age', models.CharField(blank=True, help_text='Año', max_length=100, null=True, verbose_name='Año')),
                ('month', models.CharField(blank=True, help_text='Mes', max_length=50, null=True, verbose_name='Mes')),
                ('description', models.TextField(blank=True, help_text='Descripcion', null=True, verbose_name='Descripcion')),
                ('orden', models.PositiveBigIntegerField(blank=True, help_text='Orden', null=True, verbose_name='Orden')),
                ('url', models.FileField(blank=True, null=True, upload_to='document/file', verbose_name='URL Document')),
                ('module', models.ForeignKey(blank=True, help_text='Modulo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='document.module', verbose_name='Modulo')),
                ('submodule', models.ForeignKey(blank=True, help_text='SubModulo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='document.submodule', verbose_name='Submodulo')),
            ],
            options={
                'verbose_name': ('Presupuesto',),
                'verbose_name_plural': 'Presupuesto',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Controlinterno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Nombre ', max_length=100, null=True, verbose_name='Nombre ')),
                ('name_archive', models.CharField(blank=True, help_text='Nombre de archivo', max_length=100, null=True, verbose_name='Nombre de archivo')),
                ('age', models.CharField(blank=True, help_text='Año', max_length=100, null=True, verbose_name='Año')),
                ('month', models.CharField(blank=True, help_text='Mes', max_length=50, null=True, verbose_name='Mes')),
                ('description', models.TextField(blank=True, help_text='Descripcion', null=True, verbose_name='Descripcion')),
                ('orden', models.PositiveBigIntegerField(blank=True, help_text='Orden', null=True, verbose_name='Orden')),
                ('url', models.FileField(blank=True, null=True, upload_to=document.models.documents_path, verbose_name='URL Document')),
                ('module', models.ForeignKey(blank=True, help_text='Modulo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='document.module', verbose_name='Modulo')),
                ('submodule', models.ForeignKey(blank=True, help_text='SubModulo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='document.submodule', verbose_name='Submodulo')),
            ],
            options={
                'verbose_name': ('Control Interno',),
                'verbose_name_plural': 'Control Interno',
                'ordering': ['id'],
            },
        ),
    ]
