# Generated by Django 3.2 on 2021-08-15 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_auto_20210804_1343'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accountability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountability', models.CharField(blank=True, help_text='Rendición de cuentas ', max_length=100, null=True, verbose_name='Rendición de cuentas ')),
                ('url', models.CharField(blank=True, help_text='Url', max_length=50, null=True, verbose_name='Url')),
                ('file', models.FileField(blank=True, null=True, upload_to=' document/rendicion', verbose_name='URL Document')),
            ],
            options={
                'verbose_name': ('Rendicion de cuentas',),
                'verbose_name_plural': 'Rendicion de cuentas',
                'ordering': ['id'],
            },
        ),
    ]
