# Generated by Django 3.2 on 2021-08-30 04:47

from django.db import migrations, models
import document.models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_auto_20210804_1343'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accountability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountability', models.CharField(blank=True, help_text='Rendición de cuentas ', max_length=100, null=True, verbose_name='Rendición de cuentas ')),
                ('url', models.CharField(blank=True, help_text='Url', max_length=50, null=True, verbose_name='Url')),
                ('file', models.FileField(blank=True, null=True, upload_to=' document/rendicion', verbose_name='URL Document')),
            ],
            options={
                'verbose_name': ('Rendicion de cuentas',),
                'verbose_name_plural': 'Rendicion de cuentas',
                'ordering': ['id'],
            },
        ),
        migrations.AlterField(
            model_name='document',
            name='name',
            field=models.CharField(blank=True, help_text='Nombre ', max_length=200, null=True, verbose_name='Nombre '),
        ),
        migrations.AlterField(
            model_name='document',
            name='name_archive',
            field=models.CharField(blank=True, help_text='Nombre de archivo', max_length=200, null=True, verbose_name='Nombre de archivo'),
        ),
        migrations.AlterField(
            model_name='document',
            name='url',
            field=models.FileField(blank=True, null=True, upload_to=document.models.documents_path, validators=[document.models.file_size], verbose_name='URL Document'),
        ),
    ]
